  const packages = [
  {
    title: "Hong Kong City Explorer",
    location: "Hong Kong",
    view: "HongKong.html",
    image: "img/hk22.jpg",
    description: "Discover Hong Kong’s skyline, Victoria Peak, and bustling street markets.",
    tags: ["City Tours", "Local Cuisine", "Cultural Sites", "Hotel Stay"],
    rating: 4.8,
    oldPrice: "₹1,05,000",
    newPrice: "₹92,000", 
    duration: "5 Days, 4 Nights",
    pricePerPerson: 92000
  },
  {
    title: "Hokkaido Winter Wonderland",
    location: "Sapporo & Niseko, Hokkaido",
    view: "Japan.html",
    image: "img/ho.jpg",
    description: "Experience world-class skiing, snow festivals, and fresh seafood in Japan's north.",
    tags: ["Ski Resorts", "Snow Festival", "Fresh Seafood"], 
    rating: 4.7,
    exclusive: "The price is exclusive of Hotels",
    oldPrice: "₹1,64,999",
    newPrice: "₹1,49,999", 
    pricePerPerson: 149999,
    duration: "9 Days, 8 Nights"
  },
  {
  title: "Iceland Ring Road Explorer",
  location: "Iceland",
  view: "Iceland.html",
  image: "img/ice3.jpg",
  description: "Travel the full Ring Road to see glaciers, volcanoes, fjords, and hot springs.",
  tags: ["Full Country Tour", "Nature Wonders", "Hotel Stay"],
  rating: 4.9,
  oldPrice: "₹2,25,000",
  newPrice: "₹1,98,000",
  duration: "10 Days, 9 Nights",
  pricePerPerson: 198000
},
  {
    title: "Greek Islands Explorer",
    location: "Greece",
    view: "Greece.html",
    image: "img/g4.jpg",
    description: "Sail through the Cyclades islands including Paros, Naxos, and Milos with guided tours.",
    tags: ["Island Hopping", "Beach Relaxation", "Hotel Stay"],
    rating: 4.8,
    oldPrice: "₹1,45,000",
    newPrice: "₹1,28,000", 
    duration: "8 Days, 7 Nights",
    pricePerPerson: 128000
  },
  {
    title: "Japan Highlights Grand Tour",
    location: "Japan",
    view: "Japan.html",
    image: "img/fuji.jpg",
    description: "Travel from Tokyo to Hiroshima, covering major cities, shrines, and natural wonders.",
    tags: ["City Tours", "Bullet Train Experience", "Hotel Stay"],
    rating: 4.9,
    oldPrice: "₹2,20,000",
    newPrice: "₹1,95,000",
    duration: "12 Days, 11 Nights",
    pricePerPerson: 195000
  },
  {
    title: "Japan Autumn Foliage Special",
    location: "Japan",
    view: "Japan.html",
    image: "img/k2.jpg",
    description: "Witness Japan’s stunning fall colors in Kyoto, Nikko, and Hokkaido.",
    tags: ["Seasonal Tours", "Nature Views", "Hotel Stay"],
    rating: 4.8,
    oldPrice: "₹1,85,000",
    newPrice: "₹1,62,000",
    duration: "9 Days, 8 Nights",
    pricePerPerson: 162000
  },
  {
    title: "Tropical Paradise - Maldives",
    location: "Maldives",
    view: "Maldives.html",
    image: "img/vac1.jpg",
    description: "Experience luxury in overwater bungalows with crystal clear waters and pristine beaches.",
    tags: ["5-Star Resort", "All-Inclusive", "Private Villa"],
    rating: 4.9,
    oldPrice: "₹94,999",
    newPrice: "₹79,999",
    pricePerPerson: 79999,
    duration: "7 Days, 6 Nights"
  },
  {
    title: "Hong Kong & Disneyland Family Fun",
    location: "Hong Kong",
    view: "HongKong.html",
    image: "img/hk20.jpg",
    description: "Enjoy thrilling rides, Disney magic, and cultural sightseeing.",
    tags: ["Theme Park", "Family Friendly", "Hotel Stay"],
    rating: 4.7,
    oldPrice: "₹1,25,000",
    newPrice: "₹1,10,000",
    duration: "6 Days, 5 Nights",
    pricePerPerson: 110000
  },
  
  {
    title: "Historic England & Scotland Explorer",
    location: "United Kingdom",
    view: "United kingdom.html",
    image: "img/u6.jpg",
    description: "Discover the Tower of London, Stonehenge, Edinburgh Castle, and the Scottish Highlands in one grand tour.",
    tags: ["Historical Sites", "Cultural Tours", "Hotel Stay"],
    rating: 4.8,
    oldPrice: "₹1,45,000",
    newPrice: "₹1,25,000",
    duration: "9 Days, 8 Nights",
    pricePerPerson: 125000
  },
{
  title: "UK Coastal & Countryside Retreat",
  location: "United Kingdom",
  view: "United Kingdom.html",
  image: "img/u3.jpg",
  description: "Enjoy scenic drives through Cornwall, visit the Jurassic Coast, and relax in charming seaside towns.",
  tags: ["Coastal Views", "Nature Trails", "Hotel Stay"],
  rating: 4.7,
  oldPrice: "₹1,20,000",
  newPrice: "₹1,02,000",
  duration: "7 Days, 6 Nights",
  pricePerPerson: 102000
},
  
{
  title: "Paris Art & Culture Immersion",
  location: "Paris, France",
  view: "Paris.html",
  image: "img/p5.jpg",
  description: "Explore the Louvre, Musée d'Orsay, Montmartre, and enjoy Parisian café culture with expert guides.",
  tags: ["Art Museums", "Cultural Tours", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹1,25,000",
  newPrice: "₹1,08,000",
  duration: "6 Days, 5 Nights",
  pricePerPerson: 108000
},
{
    title: "Santorini Sunset Romance",
    location: "Santorini, Greece",
    view: "Greece.html",
    image: "img/g5.jpg",
    description: "Watch world-famous sunsets from cliff-top villages with whitewashed buildings.",
    tags: ["Romantic Getaway", "Sunset Views", "Wine Tasting"],
    rating: 4.9,
    exclusive: "The price is inclusive of Hotels",
    oldPrice: "₹1,24,999",
    newPrice: "₹1,09,999",
    pricePerPerson: 109999,
    duration: "6 Days, 5 Nights"
  },
  
{
  title: "Paris & Champagne Region Experience",
  location: "Paris & Reims, France",
  view: "Paris.html",
  image: "img/p4.jpg",
  description: "Discover Paris highlights and take a luxury day trip to Champagne for vineyard tours and tastings.",
  tags: ["City Tours", "Wine Tasting", "Hotel Stay"],
  rating: 4.9,
  oldPrice: "₹1,35,000",
  newPrice: "₹1,18,000",
  duration: "7 Days, 6 Nights",
  pricePerPerson: 118000
},
{
  title: "Spiritual Varanasi & Ganges Experience",
  location: "Varanasi, India",
  view: "India.html",
  image: "img/i1.jpg",
  description: "Witness the mesmerizing Ganga Aarti, take a sunrise boat ride, and explore ancient temples in the spiritual capital of India.",
  tags: ["Boat Ride", "Temple Tours", "Cultural Experience", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹32,000",
  newPrice: "₹27,500",
  duration: "5 Days, 4 Nights",
  pricePerPerson: 27500
},
{
  title: "Meghalaya Living Root Bridges & Caves",
  location: "Shillong & Cherrapunji, India",
  view: "India.html",
  image: "img/me1.jpg",
  description: "Explore living root bridges, majestic waterfalls, and the cleanest village in Asia with guided treks and stays.",
  tags: ["Nature Trails", "Trekking", "Village Tours", "Hotel Stay"],
  rating: 4.9,
  oldPrice: "₹38,000",
  newPrice: "₹33,000",
  duration: "6 Days, 5 Nights",
  pricePerPerson: 33000
},
{
  title: "Shanghai Modern & Traditional Tour",
  location: "Shanghai, China",
  view: "China.html",
  image: "img/ch1.jpg",
  description: "Experience the blend of futuristic skyscrapers and traditional gardens with guided city tours and river cruises.",
  tags: ["City Tours", "River Cruise", "Cultural Sites", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹82,000",
  newPrice: "₹69,500",
  duration: "6 Days, 5 Nights",
  pricePerPerson: 69500
},
{
  title: "Tusheti Mountain Adventure",
  location: "Tusheti, Georgia",
  view: "Georgia.html",
  image: "img/ge2.jpg",
  description: "Explore the remote Tusheti mountains with hiking, horse riding, and homestays in traditional villages.",
  tags: ["Mountain Trek", "Horse Riding", "Village Stay"],
  rating: 4.9,
  exclusive: "The price is exclusive of Hotels",
  oldPrice: "₹74,000",
  newPrice: "₹62,000",
  duration: "6 Days, 5 Nights",
  pricePerPerson: 62000
},
{
  title: "Praslin & La Digue Discovery",
  location: "Seychelles",
  view: "Seychelles.html",
  image: "img/mau5.jpg",
  description: "Discover the natural beauty of Praslin’s Vallée de Mai and La Digue’s stunning beaches.",
  tags: ["Island Tours", "Nature Reserve", "Beach Relaxation", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹2,10,000",
  newPrice: "₹1,85,000",
  duration: "6 Days, 5 Nights",
  pricePerPerson: 185000
},
{
  title: "Complete Vietnam Journey",
  location: "Vietnam",
  view: "Vietnam.html",
  image: "img/v3.jpg",
  description: "Travel from Hanoi to Ho Chi Minh City covering Ha Long Bay, Hoi An, Hue, and Mekong Delta.",
  tags: ["City Tours", "Boat Cruise", "Cultural Experiences", "Hotel Stay"],
  rating: 4.9,
  oldPrice: "₹1,10,000",
  newPrice: "₹95,000",
  duration: "12 Days, 11 Nights",
  pricePerPerson: 95000
},
{
  title: "Iceland Highlands Adventure",
  location: "Iceland",
  view: "Iceland.html",
  image: "img/sey5.jpg",
  description: "4x4 tour through Iceland's remote highlands with guided hikes and geothermal baths.",
  tags: ["Adventure", "Hiking", "Geothermal Pools"],
  rating: 4.8,
  exclusive: "The price is exclusive of Hotels",
  oldPrice: "₹1,85,000",
  newPrice: "₹1,65,000",
  duration: "7 Days, 6 Nights",
  pricePerPerson: 165000
},
{
  title: "Thailand Grand Tour",
  location: "Thailand",
  view: "Thailand.html",
  image: "img/t3.jpg",
  description: "Experience the best of Thailand from Bangkok’s temples to Chiang Mai’s mountains and Phuket’s beaches.",
  tags: ["City Tours", "Mountain Trek", "Beach Stay", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹1,35,000",
  newPrice: "₹1,15,000",
  duration: "12 Days, 11 Nights",
  pricePerPerson: 115000
},
{
  title: "Germany Grand Explorer",
  location: "Germany",
  view: "Germany.html",
  image: "img/ice2.jpg",
  description: "From Berlin’s history to Bavaria’s castles and the Rhine Valley’s vineyards, explore Germany in depth.",
  tags: ["City Tours", "Castle Visits", "Wine Tasting", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹1,65,000",
  newPrice: "₹1,45,000",
  duration: "12 Days, 11 Nights",
  pricePerPerson: 145000
},
{
  title: "Germany Christmas Market Tour",
  location: "Germany",
  view: "Germany.html",
  image: "img/g3.jpg",
  description: "Experience Germany’s magical Christmas markets in cities like Nuremberg, Munich, and Dresden.",
  tags: ["Festival", "Shopping", "Local Cuisine"],
  rating: 4.7,
  exclusive: "The price is exclusive of Hotels",
  oldPrice: "₹1,10,000",
  newPrice: "₹95,000",
  duration: "7 Days, 6 Nights",
  pricePerPerson: 95000
},
{
  title: "Seychelles Diving Expedition",
  location: "Seychelles",
  view: "Seychelles.html",
  image: "img/sey3.jpg",
  description: "Enjoy guided scuba diving trips to vibrant coral reefs and marine life hotspots.",
  tags: ["Scuba Diving", "Marine Life", "Boat Tours"],
  rating: 4.9,
  exclusive: "The price is exclusive of Hotels",
  oldPrice: "₹2,45,000",
  newPrice: "₹2,20,000",
  duration: "7 Days, 6 Nights",
  pricePerPerson: 220000
},
{
  title: "Netherlands Art & History Experience",
  location: "Netherlands",
  view: "Netherlands.html",
  image: "img/n6.jpg",
  description: "Discover the Van Gogh Museum, Rijksmuseum, and historic canals of Amsterdam.",
  tags: ["Art Tours", "Historical Sites", "Museum Visits"],
  rating: 4.7,
  exclusive: "The price is exclusive of Hotels",
  oldPrice: "₹1,40,000",
  newPrice: "₹1,18,000",
  duration: "5 Days, 4 Nights",
  pricePerPerson: 118000
},
{
  title: "Complete UAE Explorer",
  location: "UAE",
  view: "UAE.html",
  image: "img/d3.jpg",
  description: "Experience Dubai, Abu Dhabi, Sharjah, and Fujairah with cultural tours and modern attractions.",
  tags: ["City Tours", "Cultural Sites", "Desert Safari", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹1,45,000",
  newPrice: "₹1,25,000",
  duration: "9 Days, 8 Nights",
  pricePerPerson: 125000
},
{
  title: "Lake Geneva & Swiss Riviera Escape",
  location: "Switzerland",
  view: "Switzerland.html",
  image: "img/sw3.jpg",
  description: "Relax along Lake Geneva, visit Montreux, and explore vineyards of Lavaux.",
  tags: ["Lake Views", "Wine Tours", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹2,10,000",
  newPrice: "₹1,85,000",
  duration: "6 Days, 5 Nights",
  pricePerPerson: 185000
},

{
  title: "Mauritius Luxury Wellness Retreat",
  location: "Mauritius",
  view: "Mauritius.html",
  image: "img/mau3.jpg",
  description: "Relax with spa treatments, yoga sessions, and beachfront luxury accommodations.",
  tags: ["Luxury Stay", "Spa & Wellness", "Beachfront Relaxation"],
  rating: 4.9,
  exclusive: "The price is exclusive of Hotels",
  oldPrice: "₹2,20,000",
  newPrice: "₹1,95,000",
  duration: "6 Days, 5 Nights",
  pricePerPerson: 195000
},
{
  title: "Netherlands Countryside & Windmills Tour",
  location: "Netherlands",
  view: "Netherlands.html",
  image: "img/n3.jpg",
  description: "Explore Zaanse Schans windmills, cheese farms, and traditional Dutch villages.",
  tags: ["Countryside Tours", "Cultural Experience", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹1,50,000",
  newPrice: "₹1,28,000",
  duration: "6 Days, 5 Nights",
  pricePerPerson: 128000
},
{
  title: "Finland Northern Lights & Lapland Adventure",
  location: "Finland",
  view: "Finland.html",
  image: "img/f2.jpg",
  description: "Witness the magical Northern Lights, enjoy husky sledding, and stay in glass igloos.",
  tags: ["Northern Lights", "Glass Igloo Stay", "Winter Activities"],
  rating: 4.9,
  oldPrice: "₹2,40,000",
  newPrice: "₹2,10,000",
  duration: "7 Days, 6 Nights",
  pricePerPerson: 210000
},
{
  title: "Swiss Alps & Glacier Express",
  location: "Switzerland",
  view: "Switzerland.html",
  image: "img/sw2.jpg",
  description: "Travel through the scenic Swiss Alps aboard the Glacier Express with panoramic views.",
  tags: ["Train Journey", "Mountain Views", "Hotel Stay"],
  rating: 4.9,
  oldPrice: "₹2,80,000",
  newPrice: "₹2,45,000",
  duration: "7 Days, 6 Nights",
  pricePerPerson: 245000
},
{
  title: "Amalfi Coast & Capri Escape",
  location: "Italy",
  view: "Italy.html",
  image: "img/ita.jpg",
  description: "Enjoy the breathtaking Amalfi Coast, luxury stays in Positano, and day trips to Capri.",
  tags: ["Luxury Stay", "Scenic Views", "Boat Tours"],
  rating: 4.8,
  oldPrice: "₹1,80,000",
  newPrice: "₹1,55,000",
  duration: "7 Days, 6 Nights",
  pricePerPerson: 155000
},
{
  title: "Fiji Beachfront Bliss",
  location: "Fiji",
  view: "Fiji.html",
  image: "img/mau1.jpg",
  description: "Stay at luxury beachfront resorts and enjoy crystal-clear waters with daily water activities.",
  tags: ["Beach Stay", "Water Sports", "Hotel Stay"],
  rating: 4.9,
  oldPrice: "₹2,40,000",
  newPrice: "₹2,05,000",
  duration: "7 Days, 6 Nights",
  pricePerPerson: 205000
},{
  title: "Helsinki & Finnish Archipelago Tour",
  location: "Finland",
  view: "Finland.html",
  image: "img/f1.jpg",
  description: "Explore Helsinki's culture, island hop through the Finnish archipelago, and visit charming coastal towns.",
  tags: ["City Tour", "Island Hopping", "Hotel Stay"],
  rating: 4.7,
  oldPrice: "₹1,80,000",
  newPrice: "₹1,55,000",
  duration: "6 Days, 5 Nights",
  pricePerPerson: 155000
},
{
  title: "Spanish Coastal Retreat",
  location: "Spain",
  view: "Spain.html",
  image: "img/s5.jpg",
  description: "Relax along Costa Brava with beachside stays, scenic drives, and gourmet seafood.",
  tags: ["Beach Stay", "Scenic Views", "Hotel Stay"],
  rating: 4.7,
  oldPrice: "₹1,55,000",
  newPrice: "₹1,35,000",
  duration: "7 Days, 6 Nights",
  pricePerPerson: 135000
},
{
  title: "Borneo Wildlife & Rainforest Adventure",
  location: "Malaysia",
  view: "Malaysia.html",
  image: "img/ma6.jpg",
  description: "Discover orangutans, rainforest treks, and river cruises in Malaysian Borneo.",
  tags: ["Wildlife Safari", "Nature Tours", "Adventure"],
  rating: 4.7,
  exclusive: "The price is exclusive of Hotels",
  oldPrice: "₹1,40,000",
  newPrice: "₹1,20,000",
  duration: "9 Days, 8 Nights",
  pricePerPerson: 120000
},
{
  title: "Grand Italy Highlights",
  location: "Italy",
  view: "Italy.html",
  image: "img/ven2.jpg",
  description: "Explore Rome, Florence, and Venice with guided tours, historical sites, and local cuisine.",
  tags: ["City Tours", "Heritage Sites", "Hotel Stay"],
  rating: 4.9,
  oldPrice: "₹2,10,000",
  newPrice: "₹1,85,000",
  duration: "10 Days, 9 Nights",
  pricePerPerson: 185000
},
{
  title: "Classic Spain Explorer",
  location: "Spain",
  view: "Spain.html",
  image: "img/s2.jpg",
  description: "Discover Madrid, Barcelona, and Seville with guided city tours and local cuisine.",
  tags: ["City Tours", "Cultural Experience", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹1,85,000",
  newPrice: "₹1,65,000",
  duration: "9 Days, 8 Nights",
  pricePerPerson: 165000
},
{
  title: "Best of Malaysia",
  location: "Malaysia",
  view: "Malaysia.html",
  image: "img/ma2.jpg",
  description: "Explore Kuala Lumpur, Penang, and Langkawi with cultural sites, beaches, and city life.",
  tags: ["City Tours", "Beach Stay", "Hotel Stay"],
  rating: 4.8,
  oldPrice: "₹1,20,000",
  newPrice: "₹1,05,000",
  duration: "8 Days, 7 Nights",
  pricePerPerson: 105000
},
];




